const ActionType = {
  ADD_TO_WATCH_LIST: "ADD_TO_WATCH_LIST",
  REMOVE_FROM_WATCH_LIST: "REMOVE_FROM_WATCH_LIST",
  ADD_TO_WATCHED: "ADD_TO_WATCHED",
  REMOVE_FROM_WATCHED: "REMOVE_FROM_WATCHED",
};

export default ActionType;
